import { Database, FlaskConical, Radar, Satellite, Sparkles } from "lucide-react";

import { cn } from "@/lib/utils";
import type { DataKind } from "@/types/api";

const META: Record<DataKind, { label: string; hint: string; Icon: typeof Database; cls: string }> = {
  OBSERVED: { label: "OBSERVED", hint: "Direct observations", Icon: Radar, cls: "border-secondary text-secondary" },
  REANALYSIS: { label: "REANALYSIS", hint: "Historical physically consistent reconstruction", Icon: Database, cls: "border-primary text-primary" },
  FORECAST: { label: "FORECAST", hint: "Numerical weather prediction output", Icon: Satellite, cls: "border-tertiary text-tertiary" },
  MODEL_PREDICTION: { label: "MODEL PREDICTION", hint: "Output of a statistical/ML model or baseline algorithm", Icon: Sparkles, cls: "border-on-surface-variant text-on-surface-variant" },
  SYNTHETIC_DEMO: { label: "SYNTHETIC / DEMO DATA", hint: "Generated by the scenario engine. Not a real observation or forecast.", Icon: FlaskConical, cls: "border-dashed border-error text-error" },
};

export function dataKindLabel(kind: DataKind): string {
  return META[kind].label;
}

/** Every layer, chart and card that shows data must render one of these (scientific honesty rule). */
export function DataKindBadge({ kind, compact = false, className }: { kind: DataKind; compact?: boolean; className?: string }): JSX.Element {
  const m = META[kind];
  return (
    <span
      data-testid="data-kind-badge"
      data-kind={kind}
      title={m.hint}
      className={cn("inline-flex items-center gap-1 rounded border px-1.5 py-[1px] font-mono text-label-num-sm font-semibold uppercase tracking-wide", m.cls, className)}
    >
      <m.Icon aria-hidden className="h-3 w-3 shrink-0" />
      <span>{compact && kind === "SYNTHETIC_DEMO" ? "SYNTHETIC" : m.label}</span>
      <span className="sr-only">. {m.hint}</span>
    </span>
  );
}
