"""Generate src/styles/tokens.css from the two provided design mockups.

light  = "Atmospheric Operations Workstation" mockup (Material-3-style tokens)
dark   = "AERO-TRACK 4D" landing mockup
Values are emitted as space-separated RGB channels so Tailwind can apply alpha (rgb(var(--c-x) / <alpha-value>)).
"""
LIGHT = {"on-tertiary-fixed": "#390c00", "error": "#ba1a1a", "surface-container-lowest": "#ffffff", "outline": "#747686", "secondary-fixed-dim": "#94ccff", "on-primary": "#ffffff", "error-container": "#ffdad6", "on-primary-container": "#cad3ff", "inverse-primary": "#b7c4ff", "on-tertiary-container": "#ffc9b7", "tertiary-container": "#a73400", "surface": "#f8f9ff", "secondary-container": "#7bc2ff", "surface-dim": "#cbdbf5", "secondary-fixed": "#cde5ff", "surface-bright": "#f8f9ff", "on-surface-variant": "#434655", "on-surface": "#0b1c30", "on-primary-fixed": "#001551", "inverse-surface": "#213145", "on-error-container": "#93000a", "background": "#f8f9ff", "surface-variant": "#d3e4fe", "primary": "#0037b0", "on-primary-fixed-variant": "#0039b5", "inverse-on-surface": "#eaf1ff", "on-secondary-fixed": "#001d32", "primary-fixed-dim": "#b7c4ff", "surface-container-high": "#dce9ff", "surface-container-low": "#eff4ff", "tertiary": "#7f2500", "on-tertiary-fixed-variant": "#832700", "tertiary-fixed": "#ffdbcf", "on-secondary": "#ffffff", "surface-container-highest": "#d3e4fe", "secondary": "#006399", "on-background": "#0b1c30", "on-error": "#ffffff", "surface-container": "#e5eeff", "primary-fixed": "#dce1ff", "on-secondary-container": "#004f7b", "on-tertiary": "#ffffff", "tertiary-fixed-dim": "#ffb59c", "primary-container": "#1d4ed8", "outline-variant": "#c4c5d7", "on-secondary-fixed-variant": "#004b74", "surface-tint": "#2151da"}
DARK = {"on-tertiary-container": "#7d0023", "secondary-container": "#ee9800", "outline-variant": "#3d494c", "secondary": "#ffb95f", "on-error-container": "#ffdad6", "secondary-fixed": "#ffddb8", "error-container": "#93000a", "surface-container-lowest": "#0a0e16", "secondary-fixed-dim": "#ffb95f", "on-secondary": "#472a00", "inverse-surface": "#dfe2ee", "primary-fixed": "#acedff", "on-secondary-fixed-variant": "#653e00", "tertiary-fixed-dim": "#ffb2b7", "on-secondary-container": "#5b3800", "on-primary-fixed-variant": "#004e5c", "on-tertiary": "#67001b", "outline": "#869397", "surface": "#0f131c", "on-surface-variant": "#bcc9cd", "on-tertiary-fixed-variant": "#92002a", "on-surface": "#dfe2ee", "inverse-primary": "#00687a", "on-primary": "#003640", "tertiary": "#ffb2b7", "tertiary-container": "#ff7f8b", "primary": "#4cd7f6", "on-secondary-fixed": "#2a1700", "on-primary-fixed": "#001f26", "surface-dim": "#0f131c", "primary-container": "#06b6d4", "on-tertiary-fixed": "#40000d", "on-primary-container": "#00424f", "surface-container-highest": "#31353e", "on-error": "#690005", "on-background": "#dfe2ee", "surface-container-high": "#262a33", "surface-container-low": "#181c24", "surface-bright": "#353942", "tertiary-fixed": "#ffdadb", "surface-variant": "#31353e", "surface-container": "#1c2028", "background": "#0f131c", "primary-fixed-dim": "#4cd7f6", "surface-tint": "#4cd7f6", "inverse-on-surface": "#2c3039", "error": "#ffb4ab"}
assert set(LIGHT) == set(DARK), set(LIGHT) ^ set(DARK)


def rgb(h: str) -> str:
    h = h.lstrip("#")
    return " ".join(str(int(h[i : i + 2], 16)) for i in (0, 2, 4))


def block(sel: str, d: dict[str, str]) -> str:
    return sel + " {\n" + "\n".join(f"  --c-{k}: {rgb(v)};" for k, v in sorted(d.items())) + "\n}\n"


out = "/* GENERATED by scripts/gen-tokens.py - do not edit by hand. */\n"
out += block(":root, [data-theme='light']", LIGHT) + "\n" + block("[data-theme='dark']", DARK)
open("src/styles/tokens.css", "w").write(out)
open("src/styles/token-values.json", "w").write(__import__("json").dumps({"light": LIGHT, "dark": DARK}, indent=1))
print(len(LIGHT), "tokens")
