"""Generate docs/api.md from the live OpenAPI schema (so the documentation cannot drift from the code)."""
from __future__ import annotations

import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT), str(ROOT / "backend")]

from app.core.config import Settings  # noqa: E402
from app.main import create_app  # noqa: E402


def main() -> None:
    tmp = tempfile.mkdtemp()
    app = create_app(Settings(_env_file=None, env="test", data_path=tmp, audit_log_path=f"{tmp}/a.log", demo_mode=False))
    spec = app.openapi()
    lines = [
        "# API reference (generated)", "",
        "> Generated by `python scripts/gen_api_docs.py` from the running application's OpenAPI schema. Interactive docs: `/api/v1/docs`.", "",
        "## Conventions", "",
        "- Base path `/api/v1`. Successful responses: `{ \"data\": ..., \"meta\": { \"request_id\", \"page\", \"page_size\", \"total\" } }`.",
        "- Errors: RFC 7807 `application/problem+json` with `type, title, status, code, detail, request_id` (+ `errors[]` for validation). No stack traces or filesystem paths.",
        "- Pagination: `page` (>=1), `page_size` (1-200). Sorting: `sort=-field,field`. Filtering: see each endpoint.",
        "- Every request gets an `X-Request-ID` (a valid incoming one is honoured). Timestamps are ISO-8601 **UTC** with `Z`.",
        "- Auth: `AUTH_MODE=none` (local dev) or `api_key` (`X-API-Key`; roles viewer < analyst < admin). Health probes are always open.",
        "- Rate limit and body-size limit are configurable (`RATE_LIMIT_PER_MINUTE`, `MAX_BODY_BYTES`); 429 carries `Retry-After`.",
        "- WebSocket: `GET /api/v1/ws?channels=events,alerts,jobs` -> `{type, ts_utc, request_id, payload}`; with `api_key` auth the first client message must be `{\"type\":\"auth\",\"api_key\":\"...\"}`.",
        "- All demo products carry `data_kind: SYNTHETIC_DEMO`. `severity` is an analytical category, **not** an official warning level.", "",
        "## Endpoints", "", "| Method | Path | Summary | Parameters |", "|---|---|---|---|",
    ]
    for path, ops in sorted(spec["paths"].items()):
        for method, op in ops.items():
            params = ", ".join(f"`{p['name']}`" + ("*" if p.get("required") else "") for p in op.get("parameters", []))
            body = ""
            if "requestBody" in op:
                ref = op["requestBody"]["content"]["application/json"]["schema"].get("$ref", "").split("/")[-1]
                body = f" body: `{ref}`" if ref else " body: JSON"
            summary = (op.get("summary") or op.get("operationId", "")).replace("|", "/")
            lines.append(f"| {method.upper()} | `{path}` | {summary} | {params}{body} |")
    lines += ["| WS | `/api/v1/ws` | Live updates (events, alerts, jobs) | `channels` |", ""]
    Path("docs/api.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"docs/api.md written ({sum(len(v) for v in spec['paths'].values())} operations + websocket)")


if __name__ == "__main__":
    main()
